packages:
  - admin

allowBuilds:
  esbuild: true
  '@google/genai': false
  '@prisma/engines': true
  canvas: false
  prisma: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - undici@8.8.0
  - '@tanstack/query-core@5.101.3'
  - '@tanstack/react-query@5.101.3'
  - '@google/genai@2.13.0'
